    @extends('frontend::pages.index')
@section('title')
    {{ $data['title'] }}
@endsection
@section('meta_keywords')
    {{ $data['meta_keywords'] }}
@endsection
@section('meta_description')
    {{ $data['meta_description'] }}
@endsection
@section('page-content')
    <!--Policy-->
    <section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="about-content">
                        <h4>Introduction</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>

                        <h4>Business polices</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>

                        <h4>Business polices</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>

                        <h4>Business polices</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>

                        <h4>Business polices</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>

                        <h4>Business polices</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>

                        <h4>Business polices</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores nesciunt maxime quod debitis est laboriosam quaerat maiores ipsam, officiis, dicta incidunt vel quos? Saepe esse explicabo numquam in iure asperiores? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ratione ipsam, placeat exercitationem in explicabo reprehenderit debitis pariatur sunt, aut sit illum tenetur est repellat temporibus eligendi vitae adipisci dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores impedit sed rerum doloribus! Nemo consequatur explicabo architecto dolor sed, numquam deserunt voluptatem aut voluptates! Esse nihil minima aspernatur modi quas!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/Policy-->
@endsection
